---
- name: Set facts for the role
  set_fact:
    swap_disable_cmd: swapoff -a
    fstab_path: /etc/fstab
    selinux_config_path: /etc/selinux/config
    k8s_conf_path: /etc/modules-load.d/k8s.conf
    sysctl_params:
      - name: 'net.bridge.bridge-nf-call-iptables'
        value: 1
      - name: 'net.bridge.bridge-nf-call-ip6tables'
        value: 1
      - name: 'net.ipv4.ip_forward'
        value: 1
    cri_o_1_repo_url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo"
    cri_o_2_repo_url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}/CentOS_8/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}.repo"

- name: Disable Firewalld service
  ansible.builtin.systemd:
    name: firewalld
    enabled: no
    state: stopped
  become: true

- name: Disable swap if present
  command: "{{ swap_disable_cmd }}"
  ignore_errors: yes
  changed_when: false

- name: Comment swap entry in fstab
  lineinfile:
    dest: "{{ fstab_path }}"
    regexp: 'swap'
    state: absent

- name: Set SELinux to permissive mode
  ansible.builtin.selinux:
    state: permissive
    policy: targeted

- name: Update SELinux config file
  ansible.builtin.lineinfile:
    path: "{{ selinux_config_path }}"
    regexp: '^SELINUX=enforcing$'
    line: 'SELINUX=permissive'

- name: Configure modules-load.d/k8s.conf
  ansible.builtin.blockinfile:
    path: "{{ k8s_conf_path }}"
    create: yes
    block: |
      overlay
      br_netfilter

- name: Load kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Configure sysctl parameters for Kubernetes
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
  loop: "{{ sysctl_params }}"

- name: Apply sysctl params without reboot
  ansible.builtin.command:
    cmd: sysctl --system

- name: Add Kubernetes repositories
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item | basename }}"
  become: true
  loop:
    - "{{ cri_o_1_repo_url }}"
    - "{{ cri_o_2_repo_url }}"

- name: Install Cri-O and Cri-Tools
  ansible.builtin.dnf:
    name: "cri-o"
    state: present
  become: true

- name: Enable and start Cri-O service
  ansible.builtin.systemd:
    name: crio
    enabled: yes
    state: started
  become: true

- name: Check Cri-O service status
  ansible.builtin.systemd:
    name: crio
    state: started
  register: crio_status

- name: Configure Kubernetes repository
  ansible.builtin.blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    create: yes
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v{{ VERSION }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ VERSION }}/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl

- name: Install kubelet, kubeadm, kubectl
  ansible.builtin.dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes
  become: true

- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started
  become: true
