---
# Install the Tigera Calico operator and custom resource definitions
- name: Install the Tigera Calico operator and custom resource definitions
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml

# Install Calico by creating the necessary custom resource
- name: Install Calico by creating the necessary custom resource
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml

# Wait for Calico pods to be in the running state
- name: Wait for Calico pods to be in running state
  command: kubectl wait --for=condition=Ready pods --all -n calico-system --timeout=300s
  register: result
  until: result.rc == 0
  retries: 5
  delay: 30