kubernetes_version: "v1.28"
crio_project_path: "prerelease:/main"

loadbalancer_apiserver_port: 6443

kubeadm_init_options:
  #pod-network-cidr: "192.168.0.0/16"
  #control-plane-endpoint: "kubeapi.local"
  #apiserver-advertise-address: "192.168.0.1"
  #apiserver-cert-extra-sans: "kubeapi.local"
  #kubernetes-version: "{{ kubernetes_version | regex_replace('^v', '') }}"
  #apiserver-bind-port: "6443"
  #cert-dir: "/etc/kubernetes/pki"
  #certificate-renewal: "true"
  #config: "/path/to/config.yaml"
  #cri-socket: "/var/run/dockershim.sock"
  #dry-run: "false"
  #feature-gates: "AllAlpha=false"
  #ignore-preflight-errors: "all"
  #image-repository: "k8s.gcr.io"
  #node-name: "my-node"
  #service-cidr: "10.96.0.0/12"
  #service-dns-domain: "cluster.local"
  #skip-certificate-key-print: "false"
  #skip-phases: "preflight"
  #token: "abcdef.0123456789abcdef"
  #token-ttl: "24h0m0s"
  #upload-certs: "true"

# Kube VIP
#kube_vip_enabled: false
#kube_vip_arp_enabled: false
#kube_vip_controlplane_enabled: false
#kube_vip_address: 192.168.1.2
#loadbalancer_apiserver:
#  address: "{{ kube_vip_address }}"
#  port: "{{ loadbalancer_apiserver_port }}"
#kube_vip_interface: eth0
#kube_vip_services_enabled: false
#kube_vip_dns_mode: first
#kube_vip_cp_detect: false
#kube_vip_leasename: plndr-cp-lock
#kube_vip_enable_node_labeling: false

helm_enabled: false

calico_enabled: false
# calico_repo: "https://docs.tigera.io/calico/charts"
## The following namespaces cannot be used: [calico-system calico-apiserver tigera-system tigera-elasticsearch tigera-compliance tigera-intrusion-detection tigera-dpi tigera-eck-operator tigera-fluentd calico-system tigera-manager]
# calico_namespace: "tigera-operator"
# calico_version: "v3.28.0"

longhorn_enabled: false
# longhorn_repo: "https://charts.longhorn.io"
# longhorn_namespace: "longhorn-system"
# longhorn_version: "1.6.2"